'use client';

// This page also ships as a plain React build on GitHub Pages.
/* eslint-disable next/no-img-element, next/no-html-link-for-pages */

import { useEffect, useState } from 'react';
import {
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  ArrowRight,
  BatteryCharging,
  Bluetooth,
  CircuitBoard,
  Cpu,
  FileText,
  Hammer,
  KeyboardMusic,
  Laptop,
  Lightbulb,
  MonitorCog,
  Music2,
  ShieldCheck,
  Vibrate,
} from 'lucide-react';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from '@/components/ui/carousel';

const BASELINE_CITATIONS = 6;
const CITATION_ENDPOINT =
  'https://api.semanticscholar.org/graph/v1/paper/DOI:10.1109/UR61395.2024.10597522?fields=citationCount';

const voxelScenes = [
  {
    src: './voxel-world.jpg',
    label: 'Canyon',
    alt: 'A wide block-based canyon rendered by the GPU voxel engine',
  },
  {
    src: './voxel-delta.jpg',
    label: 'River delta',
    alt: 'A river delta and islands generated by the GPU voxel engine',
  },
  {
    src: './voxel-barchan.jpg',
    label: 'Barchan dunes',
    alt: 'Barchan dunes generated in a block-based desert',
  },
  {
    src: './voxel-fjord.jpg',
    label: 'Fjord',
    alt: 'A forested fjord generated by the GPU voxel engine',
  },
];

const verificationRows = [
  {
    stage: 'Component tests',
    purpose: 'Catch mistakes before they reach the world.',
    method:
      'Check individual calculations and content rules against known answers.',
  },
  {
    stage: 'Independent instrumentation',
    purpose: 'Find terrain that looks plausible but is calculated incorrectly.',
    method:
      'Generate the same terrain on the CPU and GPU and compare the results.',
  },
  {
    stage: 'Integrated ground tests',
    purpose: 'Catch failures where otherwise working components meet.',
    method:
      'Run world loading, terrain generation, mesh creation, and visibility checks together.',
  },
  {
    stage: 'Flight tests',
    purpose: 'Expose gaps and instability as the landscape streams in.',
    method:
      'Repeat a fast flight path while nearby and distant terrain change detail.',
  },
  {
    stage: 'Repeat operations',
    purpose: 'Check that progress survives and players see the same world.',
    method:
      'Exercise saved changes, shared gameplay, and players joining an existing session.',
  },
];

const qwenLayers = [
  {
    title: 'Open-source serving base',
    text: 'syv-ai/qwen38-27b-rtx3090 supplies the tuned single-GPU vLLM deployment, profiles, and OpenAI-compatible endpoint.',
  },
  {
    title: 'Windows operations layer',
    text: 'My WPF dashboard adds start, warm, restart, stop, logs, health, and live RTX 3090 telemetry across the WSL boundary.',
  },
  {
    title: 'Client integration',
    text: 'One control surface opens six local harnesses with validated defaults and avoids duplicate terminals or browser windows.',
  },
];

const longboardFacts = [
  [
    'Power',
    '10S2P 18650 Li-ion pack, Flipsky ESC, XT90 anti-spark connector, and removable loop key.',
  ],
  [
    'Drivetrain',
    'Single motor with gearing biased toward climbing torque instead of top speed for a hilly area.',
  ],
  [
    'Packaging',
    'Foldable deck with a custom plastic enclosure heated into shape with a heat gun and cut on a bandsaw.',
  ],
  [
    'Evidence',
    'The prototype survived several years of campus use—not just a bench test.',
  ],
];

export default function Home() {
  const [citationCount, setCitationCount] = useState(BASELINE_CITATIONS);
  const [citationChecked, setCitationChecked] = useState(false);

  useEffect(() => {
    const controller = new AbortController();

    fetch(CITATION_ENDPOINT, { signal: controller.signal })
      .then((response) => {
        if (!response.ok) throw new Error('Citation lookup failed');
        return response.json();
      })
      .then((data: unknown) => {
        if (
          data &&
          typeof data === 'object' &&
          'citationCount' in data &&
          typeof data.citationCount === 'number'
        ) {
          setCitationCount(Math.max(BASELINE_CITATIONS, data.citationCount));
        }
        setCitationChecked(true);
      })
      .catch((error: Error) => {
        if (error.name !== 'AbortError') setCitationChecked(false);
      });

    return () => controller.abort();
  }, []);

  return (
    <main>
      <header className="site-header">
        <a className="wordmark" href="#top" aria-label="Neil Guan, home">
          Neil Guan
        </a>
        <nav aria-label="Primary navigation">
          <a href="#work">GPU engine</a>
          <a href="#research">Research</a>
          <a href="#systems">Qwen</a>
          <a href="#haptics">Haptic gloves</a>
          <a href="#hardware">Longboard</a>
          <a href="#workflow">AI workflow</a>
          <a href={`${import.meta.env.BASE_URL}devblog/`}>Devblog</a>
        </nav>
      </header>

      <section className="hero" id="top">
        <p className="eyebrow">Systems · Robotics · Applied AI</p>
        <h1>Systems engineering for software that is hard to verify.</h1>
        <p className="hero-copy">
          I build GPU software, robotics research, local AI infrastructure, and
          hardware—and design the tests that make ambitious work credible.
        </p>
      </section>

      <section className="work-section" id="work" aria-labelledby="work-title">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Featured project</p>
            <p className="project-kicker">mcgpu-v3 · Rust + WGSL</p>
          </div>
          <div>
            <h2 id="work-title">Beyond the one-shot Minecraft demo</h2>
            <p className="section-lede">
              AI agents can one-shot Minecraft-looking demos. This is the
              systems work beyond that first impression: a Minecraft-like world
              rebuilt around cubic chunks, GPU rendering, and nine levels of
              detail so the landscape can remain visible to the horizon while
              fast flight stays near 200 FPS. The hard part is keeping that
              asynchronous, AI-assisted pipeline fast, extensible, and correct
              while it moves.
            </p>
          </div>
        </div>

        <dl className="signal-list" aria-label="Representative engine results">
          <div>
            <dt>~200 FPS</dt>
            <dd>while fast-flying across the world</dd>
          </div>
          <div>
            <dt>9 detail levels</dt>
            <dd>close-up blocks and landscapes visible to the horizon</dd>
          </div>
          <div>
            <dt>Repeatable worlds</dt>
            <dd>recreate the same terrain to investigate and fix a bug</dd>
          </div>
        </dl>

        <Carousel
          className="voxel-gallery"
          opts={{ align: 'start', loop: true }}
          aria-label="Voxel-engine captures"
        >
          <CarouselContent>
            {voxelScenes.map((scene, index) => (
              <CarouselItem key={scene.label}>
                <figure className="gallery-frame">
                  <img
                    src={scene.src}
                    alt={scene.alt}
                    loading={index === 0 ? 'eager' : 'lazy'}
                  />
                  <figcaption>
                    <span>
                      {index + 1} / {voxelScenes.length}
                    </span>
                    <a href={scene.src} target="_blank" rel="noreferrer">
                      Open full resolution{' '}
                      <ArrowUpRight aria-hidden="true" size={15} />
                    </a>
                  </figcaption>
                </figure>
              </CarouselItem>
            ))}
          </CarouselContent>
          <CarouselPrevious className="gallery-nav gallery-prev" />
          <CarouselNext className="gallery-nav gallery-next" />
        </Carousel>

        <article className="content-platform">
          <div className="content-platform-copy">
            <p className="eyebrow">AI orchestration engineering</p>
            <h3>From an infinite world to an AI-extensible one</h3>
            <p className="orchestration-lede">
              I built a workflow for giving a Luna agent a focused content brief
              and letting it work unattended for roughly a day. It returns new
              biomes, structures, trees, or creatures with repeatable examples
              and visual reviews. Defined places to add content let me expand
              the world without reworking the renderer for every addition.
            </p>
            <ol className="orchestration-steps">
              <li>
                <strong>Brief</strong>
                <span>
                  Give each agent a clear goal and its own area to change.
                </span>
              </li>
              <li>
                <strong>Verify</strong>
                <span>
                  Return repeatable scenes, focused checks, and screenshots.
                </span>
              </li>
              <li>
                <strong>Isolate</strong>
                <span>
                  Review each contribution separately so a failed experiment
                  does not disrupt the rest of the work.
                </span>
              </li>
              <li>
                <strong>Repeat</strong>
                <span>
                  Reuse the brief, tools, and checks for the next batch of
                  content.
                </span>
              </li>
            </ol>
          </div>
          <div className="content-proof-grid asset-showcase">
            {[
              {
                src: './showcase/airship-hero.png',
                title: 'A steampunk airship, built through MineBench',
                text: 'Structure study · patchwork balloon, wooden hull, brass engines, and a glass bridge.',
                alt: 'Detailed voxel airship with a multicolored balloon and wooden hull',
                wide: true,
              },
              {
                src: './showcase/airship-detail.png',
                title: 'Construction that holds up close',
                text: 'Hull and balloon detail · inspect the same build from several angles.',
                alt: 'Close view of the airship construction and balloon detailing',
              },
              {
                src: './showcase/airship-interior.png',
                title: 'An interior as well as a silhouette',
                text: 'Bridge study · glazing, controls, lanterns, and roof beams.',
                alt: 'Furnished glass bridge inside the voxel airship',
              },
              {
                src: './showcase/nightfang.jpg',
                title: 'Nightfang · Blender geometry, Aseprite textures',
                text: 'Sharp cuboid modeling, a layered pixel-art skin, and an articulated rig. Front, side, rear, and motion views show how the design holds together.',
                alt: 'Nightfang, a dark block-built canine with amber eyes, shown from multiple angles and in walking poses',
                wide: true,
              },
            ].map((asset) => (
              <figure
                key={asset.src}
                className={asset.wide ? 'showcase-wide' : undefined}
              >
                <a
                  href={asset.src}
                  target="_blank"
                  rel="noreferrer"
                  aria-label={`Open full-resolution image: ${asset.title}`}
                >
                  <img src={asset.src} alt={asset.alt} loading="lazy" />
                </a>
                <figcaption>
                  <strong>{asset.title}</strong>
                  <span>{asset.text}</span>
                  <a href={asset.src} target="_blank" rel="noreferrer">
                    Open full resolution ↗
                  </a>
                </figcaption>
              </figure>
            ))}
          </div>
          <div className="tooling-intro">
            <p className="eyebrow">The development toolchain</p>
            <h3>Give agents tools they can actually iterate with</h3>
            <p>
              I turned repeated setup, asset editing, and review steps into
              reusable workflows. MCP (Model Context Protocol) connects agents
              to applications so they can perform specific operations, inspect
              the result, and revise it. Skills preserve the process for the
              next session.
            </p>
          </div>
          <div className="tooling-grid">
            <article>
              <span className="tooling-index">01 / Structures</span>
              <h4>MineBench</h4>
              <p>
                I replaced a custom structure harness with MineBench’s existing
                prompts, importer, converter, textures, and viewer. That moved
                the work toward improving the build itself. Adapting that
                foundation to terrain and survival play is the next step.
              </p>
              <a href={`${import.meta.env.BASE_URL}devblog/structures/`}>See the airship iterations</a>
            </article>
            <article>
              <span className="tooling-index">02 / Models & motion</span>
              <h4>Blender + MCP</h4>
              <p>
                Agents can author geometry, organize joints, animate, and render
                views through Blender. Batched geometry scripts keep heavy work
                local. Saved views and motion previews make it easier to revise
                a pose or joint without starting the model again.
              </p>
              <a href={`${import.meta.env.BASE_URL}devblog/rigging/`}>Explore creature development</a>
            </article>
            <article>
              <span className="tooling-index">03 / Pixel art</span>
              <h4>Aseprite + MCP</h4>
              <p>
                I compiled Aseprite and connected its layers, frames, palettes,
                and exports to the agent. A spell effect can be revised on its
                own layer while the character stays intact; frame previews make
                the feedback specific.
              </p>
              <a href={`${import.meta.env.BASE_URL}devblog/pixel-art/`}>See the sprite workflow</a>
            </article>
            <article>
              <span className="tooling-index">04 / Sound</span>
              <h4>Local audio tools</h4>
              <p>
                I built a local Stable Audio generation workflow and used
                Freesound through MCP for sourcing. Local trimming, filtering,
                and level adjustment handle the mechanical steps, while
                listening guides the choice of sound.
              </p>
              <a href={`${import.meta.env.BASE_URL}devblog/audio/`}>Explore the audio experiments</a>
            </article>
          </div>
          <figure className="sprite-workflow">
            <img
              src="./devblog-evidence/fox-final.png"
              alt="Six frames of an Aseprite-authored fox mage casting a blue flame spell"
              loading="lazy"
            />
            <figcaption>
              <strong>Editable animation, frame by frame.</strong> The fox,
              staff, and spell are separate layers, making small visual
              corrections practical.
            </figcaption>
          </figure>
          <div className="extensibility-panel">
            <div>
              <p className="eyebrow">Lua extensibility · in development</p>
              <h3>New gameplay without rebuilding the engine around it</h3>
            </div>
            <div>
              <p>
                I’m adding a Lua gameplay layer so abilities and creature
                decisions can live in small content packages. Rust continues to
                own movement, collision, damage, inventory, and the shared-world
                clock. Scripts compose those capabilities through a defined
                interface.
              </p>
              <p>
                The implemented host checks package versions, limits script
                resources, and supports controlled source reloads that preserve
                the previous version if a reload fails. Save and multiplayer
                integration are being developed around the same runtime; native
                gameplay validation is still in progress.
              </p>
            </div>
          </div>
          <div className="workflow-summary">
            <h4>Less setup between an idea and a useful result</h4>
            <p>
              I consolidated developer commands, added guides that point each
              feature to its implementation and checks, and moved shared
              gameplay rules into common code. Reusable authoring skills, a
              shared texture library, and repeatable review captures reduce the
              work each new session has to rediscover. Together, these changes
              let me spend more time on content and behavior, with smaller
              changes to review.
            </p>
          </div>
        </article>
      </section>

      <section
        className="testing-section"
        id="testing"
        aria-labelledby="testing-title"
      >
        <div className="case-intro">
          <p className="eyebrow">Verification architecture</p>
          <h2 id="testing-title">Testing like a flight program</h2>
          <p>
            My work at Boeing informs how I approach verification: start with
            individual components, exercise connected systems on the ground,
            then test the complete system under changing conditions. I apply
            that progression to this engine, from checking terrain calculations
            to flying through a streaming world and reopening a saved session.
          </p>
        </div>

        <div className="table-wrap">
          <table>
            <caption>From component checks to a full-world flight</caption>
            <thead>
              <tr>
                <th scope="col">Flight-test mindset</th>
                <th scope="col">Why it matters</th>
                <th scope="col">How I apply it to the engine</th>
              </tr>
            </thead>
            <tbody>
              {verificationRows.map((row) => (
                <tr key={row.stage}>
                  <th scope="row">{row.stage}</th>
                  <td>{row.purpose}</td>
                  <td>{row.method}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <aside
          className="evidence-strip"
          aria-label="Representative verification result"
        >
          <ShieldCheck aria-hidden="true" size={27} strokeWidth={1.6} />
          <p>
            <strong>A second way to check the answer.</strong> Comparing CPU and
            GPU terrain generation helps catch hidden errors even when the
            landscape looks right.
          </p>
        </aside>
      </section>

      <section
        className="research-section"
        id="research"
        aria-labelledby="research-title"
      >
        <div className="section-heading compact-heading centered-heading">
          <div>
            <p className="eyebrow">Published research</p>
            <p className="project-kicker">
              Ubiquitous Robots 2024 · First author
            </p>
          </div>
          <h2 id="research-title">Closing the sim-to-real gap</h2>
        </div>

        <article className="paper-card">
          <div className="publication-status" aria-label="Publication status">
            <span>Peer-reviewed</span>
            <span>IEEE conference paper</span>
            <span>UR 2024</span>
            <span>First author</span>
          </div>

          <div className="paper-main">
            <div className="project-icon" aria-hidden="true">
              <FileText size={28} strokeWidth={1.6} />
            </div>
            <h3>
              Impedance Matching: Enabling an RL-Based Running Jump in a
              Quadruped Robot
            </h3>
            <p className="authors">
              Neil Guan, Shangqun Yu, Shifan Zhu, and Donghyun Kim
            </p>
            <p className="paper-deck">
              Reinforcement-learning policies can look capable in simulation and
              become inconsistent on hardware because the simulated joints do
              not respond like the real machine. We measured that mismatch,
              tuned the simulation to the evidence, and transferred a
              running-jump policy to a 12 kg Mini-Cheetah Vision robot.
            </p>

            <p className="publication-record">
              This is not a private project report. It was reviewed and accepted
              as a regular paper at the 2024 21st International Conference on
              Ubiquitous Robots, then published in IEEE Xplore. It is part of
              the field&apos;s shared research record: work that other
              researchers can inspect, cite, test, and build upon.
            </p>

            <figure className="paper-figure paper-figure-jump">
              <img
                src="./paper-jump-sequence.jpg"
                alt="Published sequence showing the Mini-Cheetah robot accelerating, jumping across a marked gap, and landing"
                loading="lazy"
              />
              <figcaption>
                Published Figure 1 · The learned policy transitions from running
                to a physical jump and landing on the real robot.
              </figcaption>
            </figure>

            <div className="paper-explanation-grid">
              <section aria-labelledby="method-title">
                <p className="paper-label">The method</p>
                <h4 id="method-title">Measure first, then train</h4>
                <ol className="paper-method">
                  <li>
                    <span>01</span>
                    <div>
                      <strong>Excite the real joints</strong>
                      <p>
                        A 0.1–25 Hz chirp test records how each joint follows a
                        commanded motion.
                      </p>
                    </div>
                  </li>
                  <li>
                    <span>02</span>
                    <div>
                      <strong>Match the simulation</strong>
                      <p>
                        Bode magnitude plots and a 50 × 50 gain search identify
                        simulated PD gains with similar bandwidth and overshoot.
                      </p>
                    </div>
                  </li>
                  <li>
                    <span>03</span>
                    <div>
                      <strong>Randomize around evidence</strong>
                      <p>
                        The measured values and variance define focused training
                        ranges before the policy touches the robot.
                      </p>
                    </div>
                  </li>
                </ol>
              </section>

              <aside className="field-impact" aria-labelledby="impact-title">
                <p className="paper-label">Why it matters to robotics</p>
                <h4 id="impact-title">
                  It replaces a tuning guess with an experiment.
                </h4>
                <p>
                  Domain randomization is often chosen by intuition: vary enough
                  simulated properties and hope reality falls inside the range.
                  Ranges that are too broad or centered on the wrong model can
                  make learning harder and transfer less consistent.
                </p>
                <p>
                  Impedance matching connects classical frequency-response
                  measurement with modern robot learning. It gives researchers a
                  repeatable basis for deciding what the simulator should
                  reproduce and how much uncertainty training should
                  cover—reducing risky trial-and-error on physical hardware.
                </p>
              </aside>
            </div>

            <figure className="paper-figure paper-figure-analysis">
              <img
                src="./paper-frequency-analysis.png"
                alt="Published experimental workflow showing a fixed robot joint, chirp signal, Bode plot comparison, simulation, and frequency analysis across all joints"
                loading="lazy"
              />
              <figcaption>
                Published Figure 2 · Real and simulated joints are compared in
                the frequency domain; the best-fit simulation follows the
                measured robot near its natural frequency.
              </figcaption>
            </figure>

            <div
              className="research-contribution"
              aria-labelledby="contribution-title"
            >
              <div>
                <p className="paper-label">What the field gained</p>
                <h4 id="contribution-title">
                  A method, a modeling result, and a reusable training strategy
                </h4>
              </div>
              <ul>
                <li>
                  A frequency-domain procedure for selecting simulation gains
                  and defensible domain-randomization bounds.
                </li>
                <li>
                  Evidence that modeled rotor inertia is essential to
                  reproducing the hardware&apos;s high-frequency response.
                </li>
                <li>
                  A modified Net2Net curriculum that adds jumping while
                  preserving an existing walking skill, without reference
                  motions.
                </li>
              </ul>
            </div>

            <dl className="paper-results">
              <div>
                <dt>55 cm</dt>
                <dd>maximum cleared gap</dd>
              </div>
              <div>
                <dt>38 cm</dt>
                <dd>jump height</dd>
              </div>
              <div>
                <dt>2 m/s</dt>
                <dd>stable walking</dd>
              </div>
              <div>
                <dt>2.3×</dt>
                <dd>less jump-distance variation than naive tuning</dd>
              </div>
            </dl>
            <div className="paper-footer">
              <div>
                <strong>
                  <span aria-live="polite">{citationCount}</span> tracked
                  citations
                </strong>
                <p className="citation-note">
                  Refreshes from Semantic Scholar when its index reports a
                  higher total{citationChecked ? ' · index checked' : ''}.
                </p>
              </div>
              <div className="paper-links">
                <a
                  className="project-link"
                  href="https://ieeexplore.ieee.org/document/10597522"
                  target="_blank"
                  rel="noreferrer"
                >
                  View the IEEE publication{' '}
                  <ArrowUpRight aria-hidden="true" size={17} />
                </a>
                <a
                  className="project-link"
                  href="https://arxiv.org/abs/2404.15096"
                  target="_blank"
                  rel="noreferrer"
                >
                  Read the open paper{' '}
                  <ArrowUpRight aria-hidden="true" size={17} />
                </a>
              </div>
            </div>
          </div>

          <div className="video-grid" aria-label="Research demonstrations">
            <a
              className="video-card"
              href="https://www.youtube.com/watch?v=sz7GK5xcZuk"
              target="_blank"
              rel="noreferrer"
            >
              <img
                src="./robot-robustness.jpg"
                alt="A quadruped robot resisting a physical kick during a robustness test"
                loading="lazy"
              />
              <span>
                <strong>Kicking a robot dog to demonstrate adaptability</strong>
                <small>Robustness test · YouTube</small>
              </span>
              <ArrowUpRight aria-hidden="true" size={17} />
            </a>
            <a
              className="video-card"
              href="https://www.youtube.com/watch?v=gfBKeheAI8Y"
              target="_blank"
              rel="noreferrer"
            >
              <img
                src="./sim-to-real.jpg"
                alt="A quadruped robot performing a learned running jump"
                loading="lazy"
              />
              <span>
                <strong>The robot dog jumps: sim-to-real transfer</strong>
                <small>Running-jump test · YouTube</small>
              </span>
              <ArrowUpRight aria-hidden="true" size={17} />
            </a>
          </div>
        </article>
      </section>

      <section
        className="project-section"
        id="systems"
        aria-labelledby="systems-title"
      >
        <div className="section-heading compact-heading centered-heading">
          <div>
            <p className="eyebrow">Local AI infrastructure</p>
            <p className="project-kicker">PowerShell + WPF + WSL</p>
          </div>
          <h2 id="systems-title">Qwen Server Controls</h2>
        </div>

        <article className="qwen-card">
          <figure className="qwen-shot">
            <img
              src="./qwen-dashboard.png"
              alt="Qwen Dashboard showing server controls, RTX 3090 telemetry, and six local client harnesses"
              loading="lazy"
            />
            <figcaption>
              Native Windows control center · live operating view
            </figcaption>
          </figure>
          <div className="qwen-copy">
            <div className="project-icon" aria-hidden="true">
              <MonitorCog size={28} strokeWidth={1.6} />
            </div>
            <h3>An operations layer around a proven open-source server</h3>
            <p>
              The project builds on{' '}
              <a
                href="https://github.com/syv-ai/qwen38-27b-rtx3090"
                target="_blank"
                rel="noreferrer"
              >
                syv-ai/qwen38-27b-rtx3090
              </a>
              , then adds the Windows-side controls needed to operate it as a
              daily development service rather than a collection of commands.
            </p>
          </div>
          <div className="architecture-list">
            {qwenLayers.map((layer) => (
              <div key={layer.title}>
                <strong>{layer.title}</strong>
                <p>{layer.text}</p>
              </div>
            ))}
          </div>
        </article>
      </section>

      <section
        className="haptics-section"
        id="haptics"
        aria-labelledby="haptics-title"
      >
        <div className="section-heading compact-heading centered-heading">
          <div>
            <p className="eyebrow">Senior design</p>
            <p className="project-kicker">
              Wearable haptics · embedded systems
            </p>
          </div>
          <h2 id="haptics-title">
            Piano gloves that teach the right fingering
          </h2>
        </div>

        <article className="haptics-card">
          <div className="haptics-body">
            <div className="haptics-copy">
              <div className="project-icon" aria-hidden="true">
                <Music2 size={28} strokeWidth={1.6} />
              </div>
              <h3>Turning a MIDI score into finger-by-finger physical cues</h3>
              <p>
                Our team built two wearable gloves with five haptic actuators
                per hand. The system paired vibration cues with an illuminated
                keyboard so a learner could associate each note with the
                intended finger and key. The laptop ran the Python controller
                and served as the display: it read the keyboard&apos;s MIDI
                events, drove the separate LED strip, and sent haptic commands
                directly over Bluetooth to an Adafruit Bluefruit LE UART Friend.
                The Bluefruit relayed those commands over UART to the
                gloves&apos; ATmega328P controller.
              </p>

              <p className="role-label">My contribution</p>
              <ul className="contribution-list" aria-label="My contributions">
                <li>
                  <strong>Automatic fingering</strong>
                  <span>
                    Generated finger assignments from the score using prior
                    statistical piano-fingering research.
                  </span>
                </li>
                <li>
                  <strong>Interface and visuals</strong>
                  <span>
                    Designed the learning UI and synchronized visual feedback.
                  </span>
                </li>
                <li>
                  <strong>Desktop integration</strong>
                  <span>
                    Connected the keyboard&apos;s MIDI input, Python control
                    logic, display, LED-strip output, and Bluetooth messaging.
                  </span>
                </li>
              </ul>

              <p className="team-scope">
                <strong>Team scope:</strong> My teammates led the initial system
                and hardware design, the ATmega328P glove controller, actuator
                drivers, and LED-strip integration. The exact role of the power
                PCB is marked as uncertain in the architecture below.
              </p>

              <a
                className="project-link"
                href="https://arxiv.org/abs/1904.10237"
                target="_blank"
                rel="noreferrer"
              >
                Fingering-generation research basis{' '}
                <ArrowUpRight aria-hidden="true" size={17} />
              </a>
            </div>

            <figure className="haptic-diagram">
              <figcaption>Signal and power architecture</figcaption>

              <div
                className="haptic-signal-flow"
                aria-label="The keyboard sends MIDI key events to the laptop controller. The laptop directly drives a separate LED strip and talks over Bluetooth to the Adafruit Bluefruit LE UART Friend. The Bluefruit sends UART commands to one ATmega328P controller, which drives the haptic actuators. A lithium-ion battery and step-down power PCB feed that same controller."
              >
                <div className="architecture-map">
                  <div className="flow-node architecture-keyboard">
                    <KeyboardMusic aria-hidden="true" size={24} />
                    <span>
                      <strong>Keyboard</strong>
                      <small>MIDI key events</small>
                    </span>
                  </div>
                  <div className="flow-bridge architecture-midi">
                    <ArrowRight
                      className="flow-arrow"
                      aria-hidden="true"
                      size={24}
                    />
                    <small>MIDI</small>
                  </div>
                  <div className="flow-node flow-node-core architecture-laptop">
                    <Laptop aria-hidden="true" size={24} />
                    <span>
                      <strong>Laptop controller</strong>
                      <small>Python system · display</small>
                    </span>
                  </div>
                  <div className="flow-bridge architecture-led-bridge">
                    <ArrowRight
                      className="flow-arrow"
                      aria-hidden="true"
                      size={24}
                    />
                    <small>LED data</small>
                  </div>
                  <div className="flow-node architecture-led-strip">
                    <Lightbulb aria-hidden="true" size={24} />
                    <span>
                      <strong>Separate LED strip</strong>
                      <small>Right-key illumination</small>
                    </span>
                  </div>

                  <div className="flow-bridge flow-bridge-vertical architecture-laptop-bluefruit">
                    <ArrowDown aria-hidden="true" size={24} />
                    <small>Laptop → Bluefruit · Bluetooth haptic cues</small>
                  </div>

                  <div className="flow-node architecture-bluefruit">
                    <Bluetooth aria-hidden="true" size={24} />
                    <span>
                      <strong>Adafruit Bluefruit LE UART Friend</strong>
                      <small>BLE radio module</small>
                    </span>
                  </div>

                  <div className="flow-bridge flow-bridge-vertical architecture-uart">
                    <ArrowDown aria-hidden="true" size={24} />
                    <small>UART</small>
                  </div>

                  <div className="flow-node flow-node-core architecture-controller">
                    <Cpu aria-hidden="true" size={24} />
                    <span>
                      <strong>ATmega328P controller</strong>
                      <small>On the haptic hands</small>
                    </span>
                  </div>
                  <div className="flow-bridge architecture-haptic-bridge">
                    <ArrowRight
                      className="flow-arrow"
                      aria-hidden="true"
                      size={24}
                    />
                    <small>Haptic drive</small>
                  </div>
                  <div className="flow-node architecture-actuators">
                    <Vibrate aria-hidden="true" size={24} />
                    <span>
                      <strong>Haptic actuators</strong>
                      <small>Five per glove</small>
                    </span>
                  </div>

                  <div className="flow-node flow-node-power architecture-battery">
                    <BatteryCharging aria-hidden="true" size={24} />
                    <span>
                      <strong>General lithium-ion battery</strong>
                      <small>Controller power input</small>
                    </span>
                  </div>
                  <div className="flow-bridge flow-bridge-vertical architecture-input-power">
                    <ArrowDown aria-hidden="true" size={24} />
                    <small>Input power</small>
                  </div>
                  <div className="flow-node flow-node-power architecture-power-pcb">
                    <CircuitBoard aria-hidden="true" size={24} />
                    <span>
                      <strong>Power PCB</strong>
                      <small>Step-down converter</small>
                    </span>
                  </div>
                  <div className="flow-bridge architecture-regulated-power">
                    <ArrowUp
                      className="flow-arrow"
                      aria-hidden="true"
                      size={24}
                    />
                    <small>Regulated power</small>
                  </div>
                </div>
              </div>
            </figure>
          </div>

          <div
            className="haptic-video-grid"
            aria-label="Senior design demonstrations"
          >
            <a
              className="video-card"
              href="https://www.youtube.com/watch?v=ba2V4k7YSqk"
              target="_blank"
              rel="noreferrer"
            >
              <img
                src="./haptic-glove-review.jpg"
                alt="Haptic piano gloves operating beside a keyboard and laptop"
                loading="lazy"
              />
              <span>
                <strong>Senior design system review</strong>
                <small>Integrated prototype · YouTube</small>
              </span>
              <ArrowUpRight aria-hidden="true" size={17} />
            </a>
            <a
              className="video-card"
              href="https://www.youtube.com/watch?v=q3hkdprkflE"
              target="_blank"
              rel="noreferrer"
            >
              <img
                src="./haptic-glove-demo.jpg"
                alt="Keyboard, laptop, and haptic glove electronics during a prototype demonstration"
                loading="lazy"
              />
              <span>
                <strong>Haptic glove and light-guidance demo</strong>
                <small>Hardware demonstration · YouTube</small>
              </span>
              <ArrowUpRight aria-hidden="true" size={17} />
            </a>
          </div>
        </article>
      </section>

      <section
        className="hardware-section"
        id="hardware"
        aria-labelledby="hardware-title"
      >
        <div className="section-heading compact-heading centered-heading">
          <div>
            <p className="eyebrow">Hardware</p>
            <p className="project-kicker">Mechanical + electrical</p>
          </div>
          <h2 id="hardware-title">
            A foldable electric longboard built for hills
          </h2>
        </div>

        <article className="longboard-card">
          <div className="longboard-copy">
            <div className="project-icon" aria-hidden="true">
              <Hammer size={28} strokeWidth={1.6} />
            </div>
            <h3>Component choices driven by the route</h3>
            <p>
              The design prioritized usable climbing torque, serviceable power
              connections, and compact packaging over top-speed numbers.
            </p>
            <dl className="spec-list">
              {longboardFacts.map(([term, detail]) => (
                <div key={term}>
                  <dt>{term}</dt>
                  <dd>{detail}</dd>
                </div>
              ))}
            </dl>
          </div>
          <div className="longboard-media">
            <figure className="longboard-photo">
              <img
                src="./longboard.jpg"
                alt="Electric longboard drivetrain, motor, wiring, and custom electronics enclosure during assembly"
                loading="lazy"
              />
              <figcaption>Build-stage documentation</figcaption>
            </figure>
            <a
              className="video-card longboard-video"
              href="https://www.youtube.com/shorts/kVKNfx2d_TU"
              target="_blank"
              rel="noreferrer"
            >
              <img
                src="./longboard-test.jpg"
                alt="Electric longboard drivetrain operating during a test"
                loading="lazy"
              />
              <span>
                <strong>Watch the drivetrain test</strong>
                <small>Bench test · YouTube</small>
              </span>
              <ArrowUpRight aria-hidden="true" size={17} />
            </a>
          </div>
        </article>
      </section>

      <section
        className="ai-section"
        id="workflow"
        aria-labelledby="workflow-title"
      >
        <p className="eyebrow">How I work</p>
        <div className="ai-grid">
          <h2 id="workflow-title">
            I use AI heavily—and verify what it produces.
          </h2>
          <div>
            <p>
              Claude Code built substantial parts of the voxel renderer and
              pipeline. Codex and Sol/Luna agents contributed terrain, content
              tooling, debugging, and iteration. I define the architecture,
              constraints, acceptance criteria, test strategy, integration
              decisions, and what is allowed to ship.
            </p>
            <p>
              I also build the workflow around those agents: reusable skills,
              application connections, focused developer tools, and repeatable
              visual reviews. Independent checks help me catch mistakes as the
              pace of implementation increases.
            </p>
          </div>
        </div>
      </section>

      <footer>
        <span>Neil Guan</span>
        <span>
          GPU systems · Robotics · Wearable haptics · Applied AI · Hardware
        </span>
        <a href="#top">Back to top ↑</a>
      </footer>
    </main>
  );
}
